"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import styles from "./page.module.css";
import BackendTest from "./backend-test";

type View = "overview" | "requests" | "data" | "keys" | "audit" | "camera" | "test" | "settings";
type AccessKey = { name: string; prefix: string; scope: string; status: string };
const emptyKeys: AccessKey[] = [];
const serviceUrl = process.env.NEXT_PUBLIC_HERAFACE_API_URL || "http://127.0.0.1:18083";

export default function Home() {
  const [auth, setAuth] = useState(false), [view, setView] = useState<View>("overview"), [keys, setKeys] = useState<AccessKey[]>(emptyKeys), [health, setHealth] = useState("Đang kiểm tra");
  useEffect(() => { setAuth(localStorage.getItem("hera-auth") === "true"); const saved = localStorage.getItem("hera-keys"); if (saved) setKeys(JSON.parse(saved)); fetch(`${serviceUrl}/api/v1/health`).then((response) => response.ok ? setHealth("Đang hoạt động") : setHealth("Lỗi dịch vụ")).catch(() => setHealth("Không kết nối")); }, []);
  useEffect(() => { localStorage.setItem("hera-keys", JSON.stringify(keys)); }, [keys]);
  if (!auth) return <Login login={() => { localStorage.setItem("hera-auth", "true"); setAuth(true); }} />;
  const createKey = () => setKeys((items) => [{ name: `Khóa tích hợp ${items.length + 1}`, prefix: `hf_live_${Math.random().toString(36).slice(2, 8)}...`, scope: "recognize, checkin", status: "Đang hoạt động" }, ...items]);
  const revokeKey = (prefix: string) => setKeys((items) => items.map((key) => key.prefix === prefix ? { ...key, status: "Đã thu hồi" } : key));
  const titles: Record<View, string> = { overview: "Tổng quan backend", requests: "Giám sát request", data: "Dữ liệu embedding", keys: "Quản lý API key", audit: "Audit log", camera: "Kiểm thử webcam", test: "Kiểm tra hệ thống", settings: "Cấu hình node" };
  const nav = (next: View) => setView(next);
  return <div className={styles.app}><aside className={styles.sidebar}><div className={styles.brand}><div className={styles.mark}>H</div><div><b>HeraFace</b><small>Backend Console</small></div></div><div className={styles.workspace}><span className={styles.avatar}>A</span><div><b>HeraFace node 01</b><small>Backend · {health}</small></div></div><nav>{(["overview", "requests", "data", "keys", "audit", "test"] as View[]).map((item) => <button key={item} className={view === item ? styles.navActive : ""} onClick={() => nav(item)}>{({ overview: "◈", requests: "↗", data: "◎", keys: "⌁", audit: "◷", test: "△" } as Record<string, string>)[item]} {({ overview: "Tổng quan", requests: "Giám sát request", data: "Dữ liệu embedding", keys: "API key", audit: "Audit log", test: "Kiểm thử backend" } as Record<string, string>)[item]}</button>)}</nav><div className={styles.sidebarFoot}><div className={styles.device}><i />REST service<small>{serviceUrl}</small></div><button onClick={() => { localStorage.removeItem("hera-auth"); setAuth(false); }}>↪ Đăng xuất</button></div></aside><main className={styles.content}><header><div><span className={styles.eyebrow}>HeraFace Lite · Backend operations</span><h1>{titles[view]}</h1></div><span className={styles.userAvatar}>A</span></header>{view === "overview" && <Overview health={health} keys={keys} go={nav} />}{view === "requests" && <Requests />}{view === "data" && <Data />}{view === "keys" && <Keys keys={keys} create={createKey} revoke={revokeKey} />}{view === "audit" && <Audit />}{view === "test" && <BackendTest />}</main></div>;
}

function Login({ login }: { login: () => void }) { return <main className={styles.login}><div className={styles.loginCard}><div className={styles.mark}>H</div><span className={styles.kicker}>HeraFace Lite</span><h1>Đăng nhập console</h1><p>Quản lý runtime, request, dữ liệu và log của node nhận diện.</p><label>Email<input defaultValue="admin@hera.local" /></label><label>Mật khẩu<input type="password" defaultValue="password" /></label><button onClick={login}>Đăng nhập <span>→</span></button></div></main>; }
function Stat({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <div className={styles.stat}><small>{label}</small><strong>{value}</strong><span>{detail}</span></div>; }
function Overview({ health, keys, go }: { health: string; keys: AccessKey[]; go: (view: View) => void }) { return <><section className={styles.hero}><div><span className={styles.kicker}>Backend health</span><h2>Trung tâm vận hành HeraFace Lite.</h2><p>Giám sát node, API, model, database embedding và các request đang đi qua hệ thống.</p></div><div className={styles.health}><i /><b>{health}</b><small>{serviceUrl}</small></div></section><section className={styles.stats}><Stat label="Request hôm nay" value="0" detail="Chưa ghi nhận dữ liệu" /><Stat label="Thời gian phản hồi" value="—" detail="Chưa có mẫu đo" /><Stat label="Embedding" value="0" detail="Database cục bộ" /><Stat label="API key hoạt động" value={keys.filter((key) => key.status === "Đang hoạt động").length} detail="Quyền truy cập backend" /></section><section className={styles.twoCol}><div className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>Request monitor</span><h3>Request gần đây</h3></div><button className={styles.textButton} onClick={() => go("requests")}>Mở giám sát →</button></div><Empty text="Chưa có request nào được ghi nhận." /></div><div className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>Runtime</span><h3>Thành phần hệ thống</h3></div><span className={styles.pill}>{health}</span></div><div className={styles.apiRow}><span>REST service</span><b>{health}</b></div><div className={styles.apiRow}><span>SeetaFace6 model</span><b>Chưa kiểm tra</b></div><div className={styles.apiRow}><span>Embedding database</span><b>0 bản ghi</b></div><div className={styles.apiRow}><span>Audit storage</span><b>Chưa có dữ liệu</b></div></div></section></>; }
function Empty({ text }: { text: string }) { return <div className={styles.empty}>{text}</div>; }
function Requests() { return <section className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>Observability</span><h3>Giám sát request API</h3></div><button className={styles.secondary}>Xuất log</button></div><div className={styles.stats}><Stat label="Tổng request" value="0" detail="Từ khi khởi động" /><Stat label="Thành công" value="0" detail="HTTP 2xx" /><Stat label="Lỗi" value="0" detail="HTTP 4xx/5xx" /><Stat label="P95 latency" value="—" detail="Chưa có mẫu đo" /></div><Empty text="Chưa có request để hiển thị. Kết nối client ERP hoặc dùng trang Kiểm tra hệ thống." /></section>; }
function Data() { return <section className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>Local storage</span><h3>Dữ liệu embedding</h3></div><button className={styles.secondary}>Làm mới</button></div><div className={styles.apiRow}><span>Standard database</span><b>0 embedding</b></div><div className={styles.apiRow}><span>Mask database</span><b>0 embedding</b></div><div className={styles.apiRow}><span>Registry mapping</span><b>0 người dùng</b></div><Empty text="Database đang rỗng. Dữ liệu sẽ xuất hiện sau khi đăng ký qua API hoặc webcam." /></section>; }
function Keys({ keys, create, revoke }: { keys: AccessKey[]; create: () => void; revoke: (prefix: string) => void }) { return <section className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>Security</span><h3>API key backend</h3></div><button className={styles.primary} onClick={create}>Tạo key +</button></div>{keys.length === 0 ? <Empty text="Chưa có API key." /> : keys.map((key) => <div className={styles.keyRow} key={key.prefix}><div><b>{key.name}</b><small className={styles.mono}>{key.prefix}</small></div><span>{key.scope}</span><span className={key.status === "Đang hoạt động" ? styles.active : styles.revoked}>{key.status}</span>{key.status === "Đang hoạt động" && <button className={styles.remove} onClick={() => revoke(key.prefix)}>Thu hồi</button>}</div>)}</section>; }
function Audit() { return <section className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>Observability</span><h3>Audit log</h3></div><button className={styles.secondary}>Xuất log</button></div><Empty text="Chưa có audit log. Các thao tác runtime và API sẽ được ghi ở đây." /></section>; }
